# Spring datasource - update with your Postgres credentials
spring.datasource.url=jdbc:postgresql://localhost:5432/facultydb
spring.datasource.username=krishanu
spring.datasource.password=krishanu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port (optional)
# server.port=8080

spring.application.name=facultyManagementSystem
